/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multiplayer.pong.client;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import org.json.JSONArray;
import org.json.JSONException;

import io.socket.client.Socket;
import io.socket.emitter.Emitter;
import multiplayer.pong.dao.UsersDAO;
import multiplayer.pong.models.JTableModel;
import multiplayer.pong.socket.SocketHandler;

/**
 *
 * @author Anonymus
 */
public class LobbyFrame extends javax.swing.JFrame {
	private Socket socket;
	private UsersDAO daoUsers = new UsersDAO();
	private Vector<String> connectedPlayers = new Vector<String>();
	private Vector<String> connectedFriends = new Vector<String>();
    /**
     * Creates new form LobbyFrame
     */
    public LobbyFrame() {
    	getContentPane().setSize(new Dimension(800, 600));
    	getContentPane().setBackground(new Color(0, 0, 0));
        initComponents();
        usernamesT.setShowHorizontalLines(false);
        socket = SocketHandler.getSocket();
        handleSockets();
        refresh();
    }
    
    private void handleSockets() {
    	socket.on("userConnected", new Emitter.Listener() {
			@Override
			public void call(Object... arg0) {
				getConnectedFriends();
				refresh();
			}
		}).on("connectedPlayers", new Emitter.Listener() {
            @Override
            public void call(Object... arg0) {
                JSONArray players = (JSONArray) arg0[0];
                Vector<String> online = new Vector<String>();
                try {
                    for(int i=0; i<players.length(); i++){
                        online.add(players.getJSONObject(i).getString("username"));
                    }
                } catch(JSONException e) {}
                connectedPlayers = online;
                getConnectedFriends();
                refresh();
            }
        }).on("userDisconnected", new Emitter.Listener() {
			@Override
			public void call(Object... arg0) {
				String username = (String) arg0[0];
				connectedPlayers.remove(username);
				refresh();
			}
		});
    }
    
    private void getConnectedFriends() {
    	 // get connected friends
        Vector<String> friends = daoUsers.getFriends(SocketHandler.username);
        Vector<String> res = new Vector<String>();
        for (String friend : friends) {
        	if (connectedPlayers.contains(friend))
        		res.add(friend);
        }
        connectedFriends = res;
    }
    
    private void refresh(){
        usernamesT.setModel(new JTableModel(connectedPlayers, usernamesT.getColumnName(0)));
        friendsT.setModel(new JTableModel(connectedFriends, friendsT.getColumnName(0)));
    }
    
    public void append(String s){
        ta.append(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        usernamesT = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        usernamesT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usernamesT.setGridColor(new java.awt.Color(0, 0, 0));
        usernamesT.setInheritsPopupMenu(true);
        jScrollPane2.setViewportView(usernamesT);
        if (usernamesT.getColumnModel().getColumnCount() > 0) {
            usernamesT.getColumnModel().getColumn(0).setResizable(false);
        }
        
        JLabel lblUtilisateursEnligne = new JLabel("Utilisateurs en-ligne");
        lblUtilisateursEnligne.setForeground(new Color(255, 255, 255));
        lblUtilisateursEnligne.setFont(new Font("Trebuchet MS", Font.PLAIN, 14));
        
        ta = new JTextArea();
        ta.setEditable(false);
        
        cmdPrompt = new JTextArea();
        
        commandBtn = new JButton("Envoyer");
        commandBtn.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        
        JLabel lblLobbyPrincipal = new JLabel("Lobby Principal");
        lblLobbyPrincipal.setFont(new Font("Georgia", Font.PLAIN, 70));
        lblLobbyPrincipal.setForeground(new Color(255, 255, 255));
        lblLobbyPrincipal.setBackground(new Color(0, 0, 0));
        
        JLabel lblBienvenueUsername = new JLabel("Bienvenue, " + SocketHandler.username);
        lblBienvenueUsername.setFont(new Font("Georgia", Font.PLAIN, 18));
        lblBienvenueUsername.setForeground(Color.WHITE);
        
        scrollPane = new JScrollPane();
        
        lblAmisConnects = new JLabel("Amis connect\u00E9s");
        lblAmisConnects.setForeground(Color.WHITE);
        lblAmisConnects.setFont(new Font("Trebuchet MS", Font.PLAIN, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblLobbyPrincipal, GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.RELATED))
        				.addComponent(ta, GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(cmdPrompt, GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.RELATED)))
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        						.addComponent(commandBtn, GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        						.addComponent(lblUtilisateursEnligne, GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        						.addComponent(lblAmisConnects, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(lblBienvenueUsername)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(lblLobbyPrincipal, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblBienvenueUsername)
        					.addPreferredGap(ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
        					.addComponent(lblUtilisateursEnligne, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(ta, GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
        					.addComponent(lblAmisConnects, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        					.addGap(4)
        					.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(cmdPrompt, GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        				.addComponent(commandBtn, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
        			.addGap(19))
        );
        
        friendsT = new JTable();
        friendsT.setModel(new DefaultTableModel(
        	new Object[][] {
        	},
        	new String[] {
        		"Username"
        	}
        ));
        scrollPane.setViewportView(friendsT);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LobbyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LobbyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LobbyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LobbyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LobbyFrame().setVisible(true);
            }
        });
    }
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable usernamesT;
    private JTextArea ta;
    private JTextArea cmdPrompt;
    private JButton commandBtn;
    private JScrollPane scrollPane;
    private JTable friendsT;
    private JLabel lblAmisConnects;
}
